#Properties
additionalparam=-Xdoclint\:none
arguments=
arrow.vector.classifier=
checker.framework.version=3.42.0
checkstyle.failOnViolation=true
dep.avro.version=1.11.3
dep.fbs.version=23.5.26
dep.grpc-bom.version=1.63.0
dep.guava-bom.version=33.0.0-jre
dep.hadoop.version=3.4.0
dep.jackson-bom.version=2.17.0
dep.junit.jupiter.version=5.10.2
dep.junit.platform.version=1.9.0
dep.netty-bom.version=4.1.108.Final
dep.protobuf-bom.version=3.23.1
dep.slf4j.version=2.0.11
distMgmtSnapshotsName=Apache Development Snapshot Repository
distMgmtSnapshotsUrl=https\://repository.apache.org/content/repositories/snapshots
doclint=none
error_prone_core.version=2.24.0
errorprone.javac.version=9+181-r4173-1
forkCount=2
git.branch=7dd1d34074af176d9e861a360e135ae57b21cf96
git.build.host=Christopher-Pride-MacBook-Pro-16-inch-Nov-2023-
git.build.time=21.08.2025 @ 12\:10\:27 PDT
git.build.user.email=cpride@cpride.net
git.build.user.name=Chris Pride
git.build.version=16.1.0
git.closest.tag.commit.count=0
git.closest.tag.name=apache-arrow-16.1.0
git.commit.author.time=09.05.2024 @ 00\:21\:29 PDT
git.commit.committer.time=09.05.2024 @ 00\:21\:29 PDT
git.commit.id.abbrev=7dd1d34
git.commit.id.describe-short=apache-arrow-16.1.0-0
git.commit.id.describe=apache-arrow-16.1.0-0-g7dd1d34
git.commit.id=7dd1d34074af176d9e861a360e135ae57b21cf96
git.commit.message.full=MINOR\: [Release] Update versions for 16.1.0
git.commit.message.short=MINOR\: [Release] Update versions for 16.1.0
git.commit.time=09.05.2024 @ 00\:21\:29 PDT
git.commit.user.email=raulcumplido@gmail.com
git.commit.user.name=Raúl Cumplido
git.dirty=false
git.local.branch.ahead=NO_REMOTE
git.local.branch.behind=NO_REMOTE
git.remote.origin.url=git@github.com\:apache/arrow.git
git.tags=apache-arrow-16.1.0,go/v16.1.0,r-16.1.0
git.total.commit.count=15794
gpg.useagent=true
m2e.disableTestClasspathFlag=false
maven-compiler-plugin.version=3.12.1
maven.compiler.source=1.6
maven.compiler.target=1.6
maven.multiModuleProjectDirectory=/Users/christopher.pride/scratch/arrow
mockito.core.version=5.11.0
mockito.inline.version=5.2.0
org.apache.arrow.flight.jdbc-driver.name=Arrow Flight SQL JDBC Driver Core
org.apache.arrow.flight.jdbc-driver.version=16.1.0
org.apache.arrow.flight.name=org.apache.arrow\:arrow-flight
org.apache.arrow.flight.version=16.1.0
organization.logo=https\://www.apache.org/images/asf_logo_wide.gif
os.detected.arch=aarch_64
os.detected.bitness=64
os.detected.classifier=osx-aarch_64
os.detected.name=osx
project.build.sourceEncoding=UTF-8
project.reporting.outputEncoding=UTF-8
sourceReleaseAssemblyDescriptor=source-release
surefire.version=2.19.1
target.gen.source.path=/Users/christopher.pride/scratch/arrow/java/flight/flight-sql-jdbc-core/target/generated-sources
